// Single source of truth for every enum the app switches on. Importing these
// instead of string literals is what keeps the RBAC scope map, the Mongoose
// enums and the socket payloads from drifting apart.

export const ROLES = {
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  FIELD_AGENT: 'FIELD_AGENT',
  EXEC_ADMIN: 'EXEC_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

// Roles that authenticate with a password. Patients are OTP-only and are never
// given a passwordHash.
export const STAFF_ROLES = [
  ROLES.DOCTOR,
  ROLES.RECEPTIONIST,
  ROLES.FIELD_AGENT,
  ROLES.EXEC_ADMIN,
  ROLES.SUPER_ADMIN,
];

export const NETWORK_STATE = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEBOARDED: 'DEBOARDED',
};

export const TOKEN_STATUS = {
  WAITING: 'WAITING',
  IN_CHAMBER: 'IN_CHAMBER',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  // The doctor went off after this was booked. The token is held, not
  // cancelled — the patient chooses a new slot rather than losing their place.
  RESCHEDULE_NEEDED: 'RESCHEDULE_NEEDED',
  CANCELLED: 'CANCELLED',
};

// Statuses that mean a patient is physically still in the building. The deboard
// guard counts exactly these.
export const IN_FLIGHT_STATUSES = [TOKEN_STATUS.WAITING, TOKEN_STATUS.IN_CHAMBER];

// How far ahead a patient may book. Seven days keeps the calendar honest: a
// doctor's shifts are only meaningfully predictable about that far out.
export const BOOKING_HORIZON_DAYS = 7;

// A named half of the day. Shifts carry real times; this labels them so a
// patient reading "Morning" and a doctor marking one off mean the same thing.
export const SHIFT = {
  MORNING: 'MORNING',
  AFTERNOON: 'AFTERNOON',
  EVENING: 'EVENING',
};

export const STANDEE_STATUS = {
  UNASSIGNED: 'UNASSIGNED',
  DEPLOYED: 'DEPLOYED',
  RECLAIMED: 'RECLAIMED',
};

export const VISIT_TYPE = {
  FRESH: 'fresh',
  FOLLOWUP: 'followup',
  EMERGENCY: 'emergency',
};

export const TOKEN_SOURCE = {
  APP: 'APP',
  WALKIN: 'WALKIN',
  QR_SCAN: 'QR_SCAN',
  PHONE: 'PHONE',
};

export const SUBMISSION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CHANGES_REQUESTED: 'CHANGES_REQUESTED',
};

export const OTP_PURPOSE = {
  PATIENT_LOGIN: 'PATIENT_LOGIN',
  STAFF_LOGIN: 'STAFF_LOGIN',
  STAFF_2FA: 'STAFF_2FA',
  PHONE_CHANGE: 'PHONE_CHANGE',
  AADHAAR_LINK: 'AADHAAR_LINK',
};

export const BREAK_REASONS = ['Lunch', 'Ward Round', 'Emergency'];
export const BREAK_DURATIONS = [30, 45, 60];

export const PLAN_TYPE = {
  INDIVIDUAL: 'INDIVIDUAL',
  FAMILY_FLOATER: 'FAMILY_FLOATER',
  GROUP: 'GROUP',
  TOP_UP: 'TOP_UP',
  SUPER_TOP_UP: 'SUPER_TOP_UP',
  CRITICAL_ILLNESS: 'CRITICAL_ILLNESS',
};

// Indemnity plans do NOT stack: you claim a hospitalization against one base
// policy. Top-ups are excluded here precisely because they genuinely do stack
// above a deductible — that asymmetry is the whole point of the fragmentation rule.
export const INDEMNITY_PLANS = [PLAN_TYPE.INDIVIDUAL, PLAN_TYPE.FAMILY_FLOATER, PLAN_TYPE.GROUP];
export const TOPUP_PLANS = [PLAN_TYPE.TOP_UP, PLAN_TYPE.SUPER_TOP_UP];

export const RESPONSE_CODES = {
  OK: 'OK',
  VALIDATION: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL_ERROR',
  // domain-specific
  TOKEN_ALLOC_EXHAUSTED: 'TOKEN_ALLOC_EXHAUSTED',
  TENDER_MISMATCH: 'TENDER_MISMATCH',
  HOSPITAL_NOT_ACTIVE: 'HOSPITAL_NOT_ACTIVE',
  BOOKING_CLOSED: 'BOOKING_CLOSED',
  OTP_INVALID: 'OTP_INVALID',
  SCOPE_DENIED: 'SCOPE_DENIED',
  IN_FLIGHT_TOKENS: 'IN_FLIGHT_TOKENS',
  ILLEGAL_TRANSITION: 'ILLEGAL_TRANSITION',
  GONE: 'GONE',
};

export const SOCKET_EVENTS = {
  // client -> server
  JOIN_CHAMBER: 'JOIN_CHAMBER',
  LEAVE_CHAMBER: 'LEAVE_CHAMBER',
  JOIN_HOSPITAL: 'JOIN_HOSPITAL',
  REQUEST_QUEUE_SNAPSHOT: 'REQUEST_QUEUE_SNAPSHOT',
  // server -> client
  QUEUE_SNAPSHOT: 'QUEUE_SNAPSHOT',
  TOKEN_CREATED: 'TOKEN_CREATED',
  TOKEN_STATUS_CHANGED: 'TOKEN_STATUS_CHANGED',
  CALL_NEXT_TOKEN: 'CALL_NEXT_TOKEN',
  EXECUTE_AUDIO_ANNOUNCEMENT: 'EXECUTE_AUDIO_ANNOUNCEMENT',
  DOCTOR_BREAK_TOGGLE: 'DOCTOR_BREAK_TOGGLE',
  DOCTOR_SESSION_CHANGED: 'DOCTOR_SESSION_CHANGED',
  HOSPITAL_STATE_CHANGED: 'HOSPITAL_STATE_CHANGED',
  HOSPITAL_DEBOARDED: 'HOSPITAL_DEBOARDED',
  SUBMISSION_STATUS_CHANGED: 'SUBMISSION_STATUS_CHANGED',
  TRANSACTION_RECORDED: 'TRANSACTION_RECORDED',
};

export const AUDIT_ACTIONS = {
  WALKIN_BOOKED: 'WALKIN_BOOKED',
  TOKEN_PAID: 'TOKEN_PAID',
  TOKEN_REFUNDED: 'TOKEN_REFUNDED',
  HOSPITAL_APPROVED: 'HOSPITAL_APPROVED',
  HOSPITAL_REJECTED: 'HOSPITAL_REJECTED',
  HOSPITAL_SUSPENDED: 'HOSPITAL_SUSPENDED',
  HOSPITAL_REACTIVATED: 'HOSPITAL_REACTIVATED',
  HOSPITAL_DEBOARDED: 'HOSPITAL_DEBOARDED',
  DEBOARD_REQUESTED: 'DEBOARD_REQUESTED',
  DOCTOR_DEBOARDED: 'DOCTOR_DEBOARDED',
  STANDEE_DEPLOYED: 'STANDEE_DEPLOYED',
  STANDEE_RECLAIMED: 'STANDEE_RECLAIMED',
  WA_SETTINGS_UPDATED: 'WA_SETTINGS_UPDATED',
  SECURITY_POLICY_UPDATED: 'SECURITY_POLICY_UPDATED',
  USER_CREATED: 'USER_CREATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
};
